In [22]:
import joblib
import numpy as np
from sklearn.datasets import load_iris
iris= load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [23]:
iris.target


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [25]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [26]:
x=iris.data
y=iris.target

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

print(x_train.shape)
print(x_test.shape)

(112, 4)
(38, 4)


In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors= 3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [29]:
accuracy = knn.score(x_test, y_test)
print("accuracy is {}%".format(accuracy*100))

accuracy is 94.73684210526315%


In [30]:
y_predict= knn.predict(x_test)
y_predict

array([0, 2, 1, 0, 2, 2, 0, 1, 0, 0, 0, 2, 1, 2, 2, 2, 2, 1, 1, 0, 1, 2,
       1, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1, 1, 2, 2, 0, 2])

In [31]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_predict))

0.9473684210526315


In [32]:
model=joblib.dump(knn,'Iris model')

In [33]:
inputdata = iris.data
opdata= iris.target

In [34]:
pred= knn.predict(inputdata)
import numpy as np

In [35]:
def find_err(pred):
    
    diff_arr = np.equal(opdata, pred)
    correct_answers = np.sum(diff_arr)
    percent_diff = correct_answers / len(pred) * 100
    print("iris flower: Percentage Match is: ", percent_diff)

In [36]:
find_err(pred)

iris flower: Percentage Match is:  96.66666666666667


In [37]:
sample=[[3,2,4,5],[4,3,5,2]]
sampleop=knn.predict(sample)
sampleop

array([2, 2])

In [38]:
species =[iris.target_names[p] for p in sampleop]
print(species)

['virginica', 'virginica']
